### ISSUE TITLE
Ensure only new images are loaded

### ISSUE THREAD

**Issue by flavio** [kubic-project/container-feeder#15]
container-feeder should load only the pre-built images that have not yet been activated. This will reduce the start-up time of the service.

**Comment by PI-Victor** [comment]
@mjura do you mind if i steal this from you? on the other hand if you really want to do it i don't mind either :)

**Comment by mjura** [comment]
@PI-Victor: I think that this scenario is covered, but please test it by yourself and let me know, about your results.

**Comment by PI-Victor** [comment]
yes i can confirm this works, this issue can be closed.

**Comment by mjura** [comment]
It looks that I don't have permissions to close this issue, @flavio can you please help with this?
