### ISSUE TITLE
Whitelist of images to be imported

### ISSUE THREAD

**Issue by ereslibre** [kubic-project/container-feeder#19]
We should allow a list of images to be imported, so not all images get imported under all circumstances.

Specifically, we for example might be only interested in loading the `pause` container on the workers without having to load `velum`, `salt-minion`, `salt-api`, `salt-master`... So in this context we could run `container-feeder sles12/pause` and only the images provided in this list would be imported.

**Comment by inercia** [comment]
As the `container-feeder` is started from a service, maybe we could solve it with a drop-in unit, or maybe with some configuration file (ie, `/etc/container-feeder/images`)...

**Comment by flavio** [comment]
I would not invest more resources into container-feeder. Once we have the SUSE registry in place the images will be automatically pulled by kubernetes based on the manifest files loaded on the node.
